export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY_ID = 'GET_COUNTRY_ID';
export const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES';
export const CLEAN_DETAIL = 'CLEAN_DETAIL';
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_POPULATION = 'ORDER_BY_POPULATION';
export const POST_ACTIVITY = 'POST_ACTIVITY';
export const FILTER_BY_ACTIVITY = 'FILTER_BY_ACTIVITY';
export const GET_ACTIVITY = 'GET_ACTIVITY';

